- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git

- name: infra-role-open-ports
  src: git@github.com:status-im/infra-role-open-ports.git

- name: infra-role-swap-file
  src: git@github.com:status-im/infra-role-swap-file.git

- name: infra-role-consul-service
  src: git@github.com:status-im/infra-role-consul-service.git

- name: infra-role-systemd-timer
  src: git@github.com:status-im/infra-role-systemd-timer.git

- name: infra-role-certbot
  src: git@github.com:status-im/infra-role-certbot.git
  version: 0cac45df2ed5ba45d80111cf198f272798ba006c

- name: infra-role-nim-waku
  src: git@github.com:status-im/infra-role-nim-waku.git
  version: 19db09e5266d82a1093643fd570940429f107970

- name: infra-role-postgres-ha
  src: git@github.com:status-im/infra-role-postgres-ha.git
  version: 06804c34adb9da1d2d9da3e34d9e0520353231f2

- name: infra-role-wazuh-agent
  src: git@github.com:status-im/infra-role-wazuh-agent.git
  version: 9ba94126b5ae162f5245cef8ca8372c93323bf78
