---
- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git
  scm: git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git
  scm: git

- name: infra-role-open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  scm: git

- name: infra-role-swap-file
  src: git@github.com:status-im/infra-role-swap-file.git
  scm: git

- name: infra-role-consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  scm: git

- name: infra-role-systemd-timer
  src: git@github.com:status-im/infra-role-systemd-timer.git
  scm: git

- name: infra-role-certbot
  src: git@github.com:status-im/infra-role-certbot.git
  version: fdf310513b2dc731f30861ed8a5957b54b4422f7
  scm: git

- name: infra-role-nim-waku
  src: git@github.com:status-im/infra-role-nim-waku.git
  version: 2eaeb82a0c5aae2b80e46a7c3965809f15d9b2cc
  scm: git

- name: infra-role-postgres-ha
  src: git@github.com:status-im/infra-role-postgres-ha.git
  version: 9fbe3851b902f9873441c2b26a6d3a7e9d1525c7
  scm: git
