---
- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git
  scm: git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git
  scm: git

- name: open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  scm: git

- name: swap-file
  src: git@github.com:status-im/infra-role-swap-file.git
  scm: git

- name: consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  scm: git

- name: systemd-timer
  src: git@github.com:status-im/infra-role-systemd-timer.git
  scm: git

- name: certbot
  src: git@github.com:status-im/infra-role-certbot.git
  version: aa7daf1fe135375bb4295742e3c1566ee4aeffba
  scm: git

- name: nim-waku
  src: git@github.com:status-im/infra-role-nim-waku.git
  version: 091c9faacb507227ea0c9a350fb2af34c2a19b3e
  scm: git

- name: infra-role-postgres-ha
  src: git@github.com:status-im/infra-role-postgres-ha.git
  version: 8c10ac4c08681580dd5e60046178631579ef980e
  scm: git
